### PR TITLE
Fix flaky spec

### LINKED ISSUE #399: Fix flaky spec
Often the build fails because of this:

```
Autocomplete Manager
  when an external provider is registered
    when autocomplete-plus.suggestionListFollows is 'Word'
      it keeps the suggestion list planted at the beginning of the prefix when typing
        Expected '138px' to be '61px'.
          at [object Object].<anonymous> (/Users/travis/build/atom-community/autocomplete-plus/spec/autocomplete-manager-integration-spec.coffee:502:45)
          at Immediate._onImmediate (/Users/travis/build/atom-community/autocomplete-plus/spec/spec-helper.coffee:23:9)
```

### PR DESCRIPTION
**Pull request by benogle**
Closes #399

### CODE REVIEW

**Comment by joefitzgerald** [comment]
The appveyor build seems to always fail that test - perhaps testing on windows will yield a solution...?

**Comment by joefitzgerald** [comment]
https://github.com/joefitzgerald/packer-windows (develop branch) + https://packer.io if you need a throwaway windows VM.

**Comment by joefitzgerald** [comment]
On my Windows VM:

image

**Comment by benogle** [comment]
Ok, i'll try it on windows tomorrow. Looks like it's not getting the main flaky spec. No idea why that extra space is there.

**Comment by joefitzgerald** [comment]
So the flaky spec is failing because the actual position of the word is greater than the expected position of the word. Could this be because the width of the suggestion list is too wide, and consequently the marker is flipping from tail to head?

**Comment by benogle** [comment]
The overlay no longer flips horizontally, it shifts to accommodate the window edges. If if anything the number should be _smaller_, say if the window was too small to hold the suggestion list. But the number is larger. It's acting like a left panel (i.e. treeview) is showing up sometimes. It seems to always be greater by 77px.

**Comment by benogle** [comment]
Ok, I think I've fixed it. Basically, I added a bunch of chars so the offset doesnt trigger the overlay window boundary checking code.

**Comment by joefitzgerald** [comment]
Haha... that sounds hacky :) But yay!

**Comment by benogle** [comment]
Yeah not ideal. It's a weird browser issue I think, only manifested in the specs. This doesnt need to consume my whole day, so going with the hacky fix.

**Comment by joefitzgerald** [comment]
On the plus side, the pixel difference is now different, so you're doing something that's affecting it.

Windows:
image

**Comment by joefitzgerald** [comment]
... And my local screenshot matches the AppVeyor build: https://ci.appveyor.com/project/joefitzgerald/autocomplete-plus/build/528

**Comment by benogle** [comment]
Ok, that's a different spec

**Comment by joefitzgerald** [comment]
Oh nevermind, it's two different specs. The one that fails for me locally is the one you've been working on. The on that fails on AppVeyor was different. But they are both failing for the same reason.

**Comment by joefitzgerald** [comment]
Tests pass on my VM now. There's something weird going on with the spec running on Windows when running it interactively - randomly leaking path subscriptions:

```
C:\Users\vagrant\github\autocomplete-plus>apm test
[2360:0429/150854:INFO:CONSOLE(0)] Application server failed { [Error: listen EADDRINUSE \\.\pipe\atom-sock]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '\\\\.\\pipe\\atom-sock',
  port: -1 }
[2808:0429/150854:INFO:renderer_main.cc(212)] Renderer process started
[2360:0429/150854:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[2360:0429/150854:ERROR:cache_util.cc(132)] Unable to move cache folder C:\Users\vagrant\AppData\Roaming\Atom\GPUCache to C:\Users\vagrant\AppData\Roaming\Atom\old_GPUCache_000
[2360:0429/150854:ERROR:cache_creator.cc(133)] Unable to create cache
[2360:0429/150854:ERROR:shader_disk_cache.cc(614)] Shader Cache Creation failed: -2
warning: removing Breakpad handler out of order
[2360:0429/150854:INFO:CONSOLE(59)] "Window load time: 579ms", source: file:///C:/Users/vagrant/AppData/Local/Atom/app-0.194.0/resources/app.asar/static/index.js (59)
[2360:0429/150904:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150904:INFO:CONSOLE(259)] "Provider SampleProvider is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(259)] "Provider Object is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150905:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150906:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150908:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150908:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[2360:0429/150909:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
.......................................................F............................................................................................................................................

Autocomplete Manager
  when an external provider is registered
    select-previous event
      it selects the previous item in the list
        Error: Leaking subscriptions for paths: C:\Users\vagrant\.atom
          at ensureNoPathSubscriptions (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:221:13)
          at [object Object].<anonymous> (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:212:5)
          at Immediate._onImmediate (C:\Users\vagrant\github\autocomplete-plus\spec\spec-helper.coffee:23:9)


Finished in 14.926 seconds
196 tests, 858 assertions, 1 failure, 0 skipped


Tests failed
```

**Comment by benogle** [comment]
That error on deactivation is a huge indicator. Why cant it deactivate properly?

**Comment by joefitzgerald** [comment]
image

image

image

Looks like Atom is holding onto something in the cache, preventing the cache from being moved. After forcibly killing Atom.exe, the error goes away but the deactivation issues persist:

```
C:\Users\vagrant\github\autocomplete-plus>apm test^Z^Z
[624:0429/151324:INFO:renderer_main.cc(212)] Renderer process started
warning: removing Breakpad handler out of order
[640:0429/151325:INFO:CONSOLE(59)] "Window load time: 586ms", source: file:///C:/Users/vagrant/AppData/Local/Atom/app-0.194.0/resources/app.asar/static/index.js (59)
[640:0429/151335:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151335:INFO:CONSOLE(259)] "Provider SampleProvider is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(259)] "Provider Object is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151337:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151338:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
[640:0429/151340:INFO:CONSOLE(606)] "Error deactivating package 'autocomplete-plus'", source: c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\src\package.js (606)
.........................F...F.........................F............................................................................................................................................

Autocomplete Manager
  when an external provider is registered
    when the matched prefix is highlighted
      when the prefix does not match the word
        when the snippets package is enabled
          it does not highlight the snippet html when highlight beginning of the word
            Error: Leaking subscriptions for paths: C:\Users\vagrant\.atom
              at ensureNoPathSubscriptions (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:221:13)
              at [object Object].<anonymous> (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:212:5)
              at Immediate._onImmediate (C:\Users\vagrant\github\autocomplete-plus\spec\spec-helper.coffee:23:9)
      it highlights the prefix of the word in the suggestion list
        Error: Leaking subscriptions for paths: C:\Users\vagrant\.atom
          at ensureNoPathSubscriptions (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:221:13)
          at [object Object].<anonymous> (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:212:5)
          at Immediate._onImmediate (C:\Users\vagrant\github\autocomplete-plus\spec\spec-helper.coffee:23:9)
    select-previous event
      it selects the previous item in the list
        Error: Leaking subscriptions for paths: C:\Users\vagrant\.atom
          at ensureNoPathSubscriptions (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:221:13)
          at [object Object].<anonymous> (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:212:5)


Finished in 15.184 seconds
196 tests, 860 assertions, 3 failures, 0 skipped


Tests failed
```

**Comment by joefitzgerald** [comment]
From OSX:

```
Error deactivating package 'autocomplete-plus' TypeError: Cannot read property 'dispose' of null
  at Object.module.exports.deactivate (/Users/jfitzgerald/github/autocomplete-plus/lib/main.coffee:120:19)
  at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:601:21)
  at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:453:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.deactivatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:447:19)
  at [object Object].<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/spec/spec-helper.js:193:19)
  at [object Object].jasmine.Block.execute (/Applications/Atom.app/Contents/Resources/app.asar/vendor/jasmine.js:1070:17)
  at [object Object].jasmine.Queue.next_ (/Applications/Atom.app/Contents/Resources/app.asar/vendor/jasmine.js:2102:31)
  at [object Object].onComplete (/Applications/Atom.app/Contents/Resources/app.asar/vendor/jasmine.js:2098:18)
  at [object Object].jasmine.WaitsForBlock.MultiCompletion.attemptCompletion (/Applications/Atom.app/Contents/Resources/app.asar/vendor/jasmine.js:2648:8)
  at /Applications/Atom.app/Contents/Resources/app.asar/vendor/jasmine.js:2658:10
  at process._tickCallback (node.js:367:9)
```

**Comment by joefitzgerald** [comment]
Requires existential check on `@subscriptions`.

**Comment by joefitzgerald** [comment]
Still leaking paths...

```
C:\Users\vagrant\github\autocomplete-plus>git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/atom-community/autocomplete-plus
   390e0d6..11fc373  bo-fix-flay-spec -> origin/bo-fix-flay-spec
Updating 390e0d6..11fc373
Fast-forward
 lib/main.coffee | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

C:\Users\vagrant\github\autocomplete-plus>apm test
[776:0429/151828:INFO:renderer_main.cc(212)] Renderer process started
warning: removing Breakpad handler out of order
[1708:0429/151829:INFO:CONSOLE(59)] "Window load time: 580ms", source: file:///C:/Users/vagrant/AppData/Local/Atom/app-0.194.0/resources/app.asar/static/index.js (59)
[1708:0429/151838:INFO:CONSOLE(259)] "Provider SampleProvider is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
[1708:0429/151839:INFO:CONSOLE(259)] "Provider Object is not valid", source: /C:/Users/vagrant/github/autocomplete-plus/lib/provider-manager.coffee (259)
..............................F.....................................................................................................................................................................

Autocomplete Manager
  when an external provider is registered
    when a replacementPrefix is not specified
      it replaces with the default input prefix
        Error: Leaking subscriptions for paths: C:\Users\vagrant\.atom
          at ensureNoPathSubscriptions (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:221:13)
          at [object Object].<anonymous> (c:\Users\vagrant\AppData\Local\Atom\app-0.194.0\resources\app.asar\spec\spec-helper.js:212:5)
          at Immediate._onImmediate (C:\Users\vagrant\github\autocomplete-plus\spec\spec-helper.coffee:23:9)


Finished in 14.433 seconds
196 tests, 858 assertions, 1 failure, 0 skipped


Tests failed
```

**Comment by joefitzgerald** [comment]
So you force pushed over the `@subscriptions?.dispose()` change I committed, that is required to prevent the deactivation error.

**Comment by joefitzgerald** [comment]
If you rebased, then we should be good: 17e892a5d27cf7906018ad3ae3a9f4bd1715ed85 has this.

**Comment by benogle** [comment]
Yeah, I rebased on master. I remembered that commit come through, and it solved it for me. I didnt see your commit on here.

**Comment by joefitzgerald** [comment]
All good. Still getting random path leakage. It's possible it's just "My Machine :tm:" but if you see this come up in the AppVeyor build, it's a spec-helper issue on Windows.

**Comment by joefitzgerald** [comment]
:+1: to merge.

File: spec/autocomplete-manager-integration-spec.coffee [hunk 1]
```diff
@@ -503,39 +504,41 @@ describe 'Autocomplete Manager', ->
 
       it "keeps the suggestion list planted at the beginning of the prefix when typing", ->
         overlayElement = null
-        editor.insertText('x')
+        # Lost of x's to keep the margin offset away from the left of the window
```
Comment (joefitzgerald) [inline spec/autocomplete-manager-integration-spec.coffee]: `Lost` > `Lots`
