### PR TITLE
Singleton AutocompleteManager, Separate View's Model From AutocompleteManager

### LINKED ISSUE #29: Add priority stuff to suggestions
As propsed by @pjv, we should add some priority stuff to the suggestions:

* matches from the current language syntax file
* matches from snippets for the current language
* matches from word list from the current file buffer

### LINKED ISSUE #36: Modify Provider / Suggestion API To Be Asynchronous
Curently, [runAutocompletion](https://github.com/saschagehlich/autocomplete-plus/blob/c338b59ede0a8b17ad4b965407c6c7038d77f136/lib/autocomplete-view.coffee#L129-L155) is an synchronous API, calling each Provider in order for suggestions. It might be more appropriate to make this an asynchronous, event-driven API. This presents obvious challenges for aggregation of suggestions, but should discourage any misbehaving providers from blocking unnecessarily.

### LINKED ISSUE #78: Option to disable on comment lines.
Can we please get an option to disable auto complete inside of comments?

### LINKED ISSUE #84: Autocomplete showing duplicate results
This is more of a question than an issue, but I'm seeing duplicate results when getting autocomplete results. I would really would like to only see Emmet results, is there any setting where I could do that?

snap 2014-06-23 at 10 15 00 319x107

### LINKED ISSUE #88: Suppress Activation For Some Scopes, Make Scopes Configurable
A feature to ignore certain words would be really nice.  For example, when in a Ruby project, anytime I type the word `end`, I get a autocomplete window with `extend, respond_to`.  It would be nice if I could tell autocomplete+ to close when certain words are typed.

To be really specific about my issue... I usually type `end`, then immediately use the up arrow to return to the previous line.  With autocomplete+ enabled, pressing the up arrow cycles the choices in the window instead of return the cursor to the previous line.

Thanks!

### LINKED ISSUE #90: Need api: disable FuzzyProvider,  let typedText.length > 0
> https://github.com/yongkangchen/atom-ctags/issues/3

1、I need a provider api to `disable just FuzzyProvider`
for reason is: atom-ctags auto update symbols when file save, there no need to enable FuzzyProvider. But still need autocomplete-snippets, so I can't use `exclusive` to exclusive all other provider. 

2、I need a provider api to let `typedText.length > 0` instead of `typedText.length is 1` in [autocomplete-view.coffee#L188](https://github.com/saschagehlich/autocomplete-plus/blob/master/lib/autocomplete-view.coffee#L188)
for reason is: when input `(`,  [bracket-matcher](https://github.com/atom/bracket-matcher) auto insert `)`, lead to `typedText.length == 2`, and I need autocomplete to show symbol for pre word which include function param.

### LINKED ISSUE #107: don't autocomplete non-code
strings, comments

### LINKED ISSUE #125: Doesn't support `undo` properly
When a suggestion is inserted and I `undo` the last command (i.e. press *Cmd+Z*), I expect that the autocompletion is removed and the word before autocompletion is restored. Instead the complete word is removed.

### LINKED ISSUE #132: Commenting a text triggers autocomplete
Autocomplete box opens when pressing Cmd + "/" while cursor is in the middle/end of any word in line.

### LINKED ISSUE #171: Make autocomplete scope aware for provider api
Ideally a given scope in a language would give us hints as to what providers to use.

For instance, the autocomplete-paths provider could automatically be enabled when a language denotes that a given point in a code has a `path` or `filename` scope. 

Additionally, we should consider possibly allowing users to globally disable common scopes that they may or may not want autocomplete to engage.  For example #107 could be solved by disabling autocomplete on the `comment` scopes

### LINKED ISSUE #188: Incorrect inserted suggestion
I found an issue: when I confirm the suggestion using keyboard shortcut, it inserts the word twice. Mouse-confirm is okay.

Correct behaviour (confirming with mouse):
ac-p1

The bug (confirming with enter):
ac-p2

This is not observable immediately, Atom relaunch fixes it. I'm not sure how to reproduce.
The issue only appears after several hours.

Update: it seems the extension adds that many letters, how many I *did not* type.
Example:
I type *reques* and confirm: it inserts *RREQUESTS*
I type *r* and confirm: it inserts *REQUESTREQUESTS*

Environment:

OSX 10.10
Atom 0.165.0
autocomplete-plus 1.1.0
// I have observed this issue on version 1.0.0 too

```
$ apm list
├── Stylus@0.4.0
├── atom-html-preview@0.1.3
├── atom-prettify@0.1.0
├── autoclose-html@0.13.0
├── autocomplete-plus@1.0.0
├── coffee-compile@0.8.4
├── color-picker@1.2.6
├── css-color-highlighting@0.2.4
├── editorconfig@0.2.2
├── error-status@0.3.1
├── file-icons@1.4.3
├── git-plus@4.3.0
├── highlight-line@0.9.2
├── highlight-selected@0.7.0
├── html2jade@0.7.0
├── language-ejs@0.1.0
├── language-jade@0.3.0
├── language-jsx@0.1.4
├── language-latex@0.4.1
├── language-r@0.1.1
├── line-ending-converter@0.4.0
├── minimap@3.4.9
├── minimap-color-highlight@3.0.3
├── minimap-find-and-replace@3.0.4
├── minimap-git-diff@3.0.11
├── minimap-highlight-selected@3.0.0
├── monokai@0.9.0
├── pane-layout-plus@0.4.0
├── pretty-json@0.3.1
├── preview-tabs@0.1.6
├── save-session@0.11.2
├── ssh-config@0.10.0
├── todo-show@0.6.0
└── view-tail-large-files@0.1.6
```

`keymap.cson`:
```
".autocomplete-plus":
  "enter": "autocomplete-plus:confirm"
```

### LINKED ISSUE #190: Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined
[Enter steps to reproduce below:]

1. Open Atom v 0.166.0
2. Error comes up in the top-left corner
(Tab completion refused to work in the previous version of Atom but now seems to be fixed again, so the issue doesn't seem to be blocking)

**Atom Version**: 0.166.0
**System**: Mac OS X 10.9.5
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1325

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1325:34)
  at AutocompleteManager.module.exports.AutocompleteManager.runAutocompletion (/Users/svanbastenbatenburg/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:168:39)
  at /Users/svanbastenbatenburg/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "wrap-guide",
      "color-gutter"
    ],
    "themes": [
      "seti-ui",
      "firstlight-syntax"
    ],
    "projectHome": "/Users/svanbastenbatenburg/projects/"
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.2
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
block-travel, v0.10.0
firstlight-syntax, v0.0.0
linter, v0.9.1
linter-pep8, v0.1.0
minimap, v3.5.0
open-last-project, v0.1.1
project-palette-finder, v2.4.7
seti-ui, v0.5.1
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

### LINKED ISSUE #191: Unable to use tabs/commenting shortcut/press enter after updating to 1.1.0 and atom 0.168
After 0.168 autocomplete plus suddenly is grabbing most of my non alphanumeric keys for itself and not letting go. List of things not working with autocomplete-plus enabled.

* enter key, have to press alt-enter to return a new line
* pressing tab
* Ctrl/Command + / doesn't work

What's going on?

### LINKED ISSUE #194: layout/overflow issue in suggestion-list
Commit 3985780f7fb708582f2b9df41b10b932ba0ee2e6 puts `overflow: visible` on the `list-group`. This makes the items overflow out of the box that is max 200px high. The commit seems to solve a problem, but it's a bit messy and causes [a problem](https://github.com/braver/isotope-ui/issues/7) in isotope-ui where the suggestion box is not expanding.

I see two possible solutions:

1. set overflow back to auto
2. or if the list should grow, remove the max-height by setting `max-height: none` on the list-group

screen shot 2015-01-15 at 09 23 15

### LINKED ISSUE #196: FuzzyProvider Should Remove Words Which Are No Longer In Any Open Buffer
* Open a new buffer.
* Write `bogos = 1`, then press enter.
* Correct that word to "bogus" by replacing one letter.

Now it's only autocompleting "bogos" and not "bogus". If you write "bogus" later, both versions are in the autocompletion list.

There's no way to remove words with typos without closing the document or rebooting atom (if configured to use other buffers).

When typing a word then pressing enter, it's not added to autocompletion (hence the `= 1` in the example).

### LINKED ISSUE #198: Pastes twice
I am having a problem on Atom v169 on Windows/Linux with AutoComplete-Plus package. Whenever this package is enabled, everytime I paste stuff, it gets pasted twice.

Not sure if it's a problem in some other package. Please advice.

### LINKED ISSUE #200: It disturbs the transforming with Google IME
When I'm using the Google IME, the Autocomplete-Plus shows a suggestions and the ATOM deletes untransformed words.
So I have to set the "Show Suggestions On Keystroke" to off, which is too inconvenient.

Showing suggestions, determine if IME is on, the Autocomplete-Plus should cancel to do it.

### PR DESCRIPTION
**Pull request by joefitzgerald**
This PR seeks to change `autocomplete-plus` such that `AutocompleteManager` is a singleton.

- [x] Rename `select-list-element` to `suggestion-list-element`
- [x] Add `suggestion-list`
- [x] Modify `main.coffee` to manage a single `AutocompleteManager` instance
- [x] Track providers in an associative array, associating providers with scopes
- [x] Modify provider registration functions to discard editor binding during provider registration
- [x] Determine scope(s) for editor provided during provider registration
- [x] Manage `suggestion-list-element` across editors
- [x] Ensure decoration and view migrate across editors without problems
- [x] Make modest FuzzyProvider enhancements
- [x] Add service-hub based API
- [x] Track provider registrations with scoped-property-store
- [x] Deprecate Provider and Suggestion

--

- Fixes #29 
- Fixes #36 
- Fixes #78
- Fixes #84 
- Fixes #88 
- Fixes #90
- Fixes #107
- Fixes #125
- Fixes #132
- Fixes #171
- Fixes #184 
- Fixes #188
- Fixes #190
- Fixes #191
- Fixes #194 
- Fixes #196 
- Fixes #198
- Fixes #200

### CODE REVIEW

**Comment by joefitzgerald** [comment]
@nathansobo This PR integrates `service-hub` into `autocomplete-plus`. Would appreciate a review of the portion that integrates it, if you're open (in `autocomplete-manager.coffee`).

**Comment by nathansobo** [comment]
@joefitzgerald Awesome. I'll take a look today.

File: lib/autocomplete-manager.coffee [hunk 1]
```diff
@@ -1,139 +1,140 @@
...
-
-  onDoConfirmSelection: (cb) ->
-    @emitter.on 'do-confirm-selection', cb
-
-  selectNext: =>
-    @emitter.emit 'do-select-next'
-
-  onDoSelectNext: (cb) ->
-    @emitter.on 'do-select-next', cb
+    return unless currentPaneItem?
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: currentPaneItem could be something other than an editor.  In which case we should deregister the current editor and cancel any current autocomplete.

File: lib/autocomplete-manager.coffee [hunk 2]
```diff
@@ -1,139 +1,140 @@
...
+    @bufferSavedSubscription = @buffer.onDidSave(@bufferSaved)
+    @bufferChangedSubscription = @buffer.onDidChange(@bufferChanged)
 
-  onDoSelectPrevious: (cb) ->
-    @emitter.on 'do-select-previous', cb
+    # Subscribe to editor events:
+    # Close the overlay when the cursor moved without changing any text
+    @editorCursorMovedSubscription = @editor.onDidChangeCursorPosition(@cursorMoved)
+    # TODO: Is this the event for switching tabs?
+    @didChangeTabsSubscription = @editor.onDidChangeTitle(@hideSuggestionList)
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: i really think you can probably take this event out, as long as we are detaching from the editors when they are no longer active this should not be necessary.

File: lib/autocomplete-manager.coffee [hunk 3]
```diff
@@ -1,139 +1,140 @@
...
+    @showSuggestionList()
+
+  providersForScopes: (scopes) =>
+    return [] unless scopes?
+    return [] unless @scopes
+    providers = []
+    for scope in scopes
+      if @scopes[scope]?
+        providers = _.union(providers, @scopes[scope])
+    providers.push(@fuzzyProvider) unless _.size(providers) > 0
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: :+1:

File: lib/autocomplete-manager.coffee (hunk 2 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fair. Will remove.

File: lib/autocomplete-manager.coffee (hunk 1 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Yes, that's still a TODO. How should we restrict what a 'valid' editor is?

File: lib/autocomplete-manager.coffee [hunk 4]
```diff
@@ -1,183 +1,111 @@
...
-
-  onDoConfirmSelection: (cb) ->
-    @emitter.on 'do-confirm-selection', cb
+    return unless currentPaneItem?
+    return if currentPaneItem is @editor
 
-  selectNext: =>
-    @emitter.emit 'do-select-next'
+    # Stop listening to buffer events
+    @bufferSavedSubscription?.dispose()
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Minor suggestion: Could you bundle up the various disposables associated with an editor/buffer into a single `CompositeDisposable`?

File: lib/autocomplete-manager.coffee [hunk 5]
```diff
@@ -1,183 +1,111 @@
...
-  onDoSelectNext: (cb) ->
-    @emitter.on 'do-select-next', cb
+    # Stop listening to editor events
+    @editorCursorMovedSubscription?.dispose()
 
-  selectPrevious: =>
-    @emitter.emit 'do-select-previous'
+    # Disqualify invalid pane items
+    # TODO
+    if false
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: You should be able to do an `instanceof` check against the `TextEditor` class exported from the `atom` module.

File: lib/autocomplete-manager.coffee [hunk 6]
```diff
@@ -1,183 +1,111 @@
...
+    @buffer = @editor.getBuffer()
 
-    return false
+    # Subscribe to buffer events:
+    @bufferSavedSubscription = @buffer.onDidSave(@bufferSaved)
+    @bufferChangedSubscription = @buffer.onDidChange(@bufferChanged)
 
+    # Subscribe to editor events:
+    # Close the overlay when the cursor moved without changing any text
+    @editorCursorMovedSubscription = @editor.onDidChangeCursorPosition(@cursorMoved)
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Why does this need to be an instance variable? Would a local variable suffice?

File: lib/autocomplete-manager.coffee [hunk 7]
```diff
@@ -1,183 +1,111 @@
...
 
   # Private: Finds suggestions for the current prefix, sets the list items,
   # positions the overlay and shows it
   runAutocompletion: =>
-    @cancel()
-    @originalSelectionBufferRanges = @editor.getSelections().map (selection) -> selection.getBufferRange()
+    @hideSuggestionList()
+    return unless @editor?
+    return unless @buffer?
+    return if @currentFileBlacklisted()
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Minor grammar-OCD suggestion: `::isCurrentFileBlackListed`

File: lib/autocomplete-manager.coffee [hunk 8]
```diff
@@ -1,183 +1,111 @@
...
     @originalCursorPosition = @editor.getCursorScreenPosition()
     return unless @originalCursorPosition?
-    buffer = @editor?.getBuffer()
-    return unless buffer?
+    currentScopes = @editor.scopeDescriptorForBufferPosition(@originalCursorPosition)?.scopes
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: You should use `.getScopesArray()` to access the scopes array and avoid accessing the property, which isn't part of the public API.

File: lib/autocomplete-manager.coffee [hunk 9]
```diff
@@ -149,141 +150,190 @@ class AutocompleteManager
...
     else
-      @cancel()
-
-  # Private: Replaces the current prefix with the given match
+      @hideSuggestionList()
+
+  #  |||              |||
+  #  vvv PROVIDER API vvv
+
+  registerProviderForGrammars: (provider, grammars) =>
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: We should break this out into a ProviderManager component.  Since the job of the AutocompleteManager is to handle the editor and editor interactions.

File: lib/autocomplete-manager.coffee [hunk 10]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
 
     # No suggestions? Cancel autocompletion.
     return unless suggestions.length
+    @suggestionList?.changeItems(suggestions)
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Will this ever be `undefined`?

File: lib/autocomplete-manager.coffee (hunk 4 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: We do maintain a `CompositeDisposable` but we cannot use that for buffer / editor events, because we have a single `AutocompleteManager` which is subscribing / unsubscribing as pane items change.

Consequently we need to explicitly track those subscriptions - hence the code is the way it is.

File: lib/autocomplete-manager.coffee [hunk 11]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
+    @showSuggestionList()
+
+  providersForScopes: (scopes) =>
+    return [] unless scopes?
+    return [] unless @scopes
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: I know this was here before, but still wondering: Will this ever be `undefined`?

File: lib/autocomplete-manager.coffee (hunk 6 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Same explanation as the buffer subscription above. A single `AutocompleteManager` tracks all editors / buffers (but only one of each at a time) for the lifetime of the package's activation.

File: lib/autocomplete-manager.coffee (hunk 3 above)
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Not sure I understand what's going on with the scope matching here? Can you explain it? Looks like you're matching every individual scope from a scope descriptor against the contents of a hash, but I could be wrong. My instinct would be that you'd have the providers registered with scope *selectors*, then match them against the current scope *descriptor* to determine which providers apply.

File: lib/autocomplete-manager.coffee (hunk 7 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in 2f7b102671b2dc670976673b9f9753d27dfa23d0

File: lib/autocomplete-manager.coffee [hunk 12]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
-  # Private: Focuses the hidden input, starts listening to keyboard events
-  setActive: ->
-    @addKeyboardInteraction()
-    @active = true
+  # Private: Gets called when the user successfully confirms a suggestion
+  #
+  # match - An {Object} representing the confirmed suggestion
+  confirm: (match) =>
+    return unless @editorHasFocus()
+    return unless match?.provider?
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Curious, when would the match not have a provider?

File: lib/autocomplete-manager.coffee (hunk 9 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: > AutocompleteManager is to handle the editor and editor interactions.

Is it? I mean, I suppose it could be its sole purpose, but I think the Provider API makes sense there too, at least for now.

File: lib/autocomplete-manager.coffee (hunk 4 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: We could create a composite disposable when doing editor subscriptions and only store an clear that one when we detatch from a given editor.  If we have to bind to more events in the future this would make the pattern more explicit.

File: lib/autocomplete-manager.coffee (hunk 10 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Shouldn't be, unless someone uses a disposed `AutocompleteManager`.

File: lib/autocomplete-manager.coffee [hunk 13]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
+    return unless @editor?
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Should this be the first check?

File: lib/autocomplete-manager.coffee [hunk 14]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
-    @delayTimeout = setTimeout @runAutocompletion, delay
+    @hideSuggestionList()
 
-  # Private: Gets called when the cursor has moved. Cancels the autocompletion if
-  # the text has not been changed and the autocompletion is
-  #
-  # data - An {Object} containing information on why the cursor has been moved
-  cursorMoved: (data) =>
-    @cancel() unless data.textChanged
+    return unless replace
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Do you want a `?` here in case the replacement is an empty string? I admit it's a weird case but might be nice to allow it just in case.

File: lib/autocomplete-manager.coffee [hunk 15]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
+    @replaceTextWithMatch(match)
+    @editor.getCursors()?.forEach (cursor) ->
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: What's the purpose of this loop? Seems like you're getting and setting the same position.

File: lib/autocomplete-manager.coffee (hunk 12 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: You'd be surprised how often it occurs during development of a new provider. This will likely change soon, as we're going to switch to a non-`Provider` (class) based approach.

File: lib/autocomplete-manager.coffee [hunk 16]
```diff
@@ -188,66 +116,46 @@ class AutocompleteManager
...
-    editorView = @editorView
-    editorView = editorView[0] if editorView.jquery
-    return editorView.hasFocus()
-  # Private: Gets called when the user saves the document. Cancels the
-  # autocompletion
-  editorSaved: =>
-    return unless @editorHasFocus()
-    @cancel()
+  showSuggestionList: ->
+    @suggestionList?.show(@editor)
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Do we need the `?` here?

File: lib/autocomplete-manager.coffee (hunk 13 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Probably.

File: lib/autocomplete-manager.coffee (hunk 15 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Think that was taken from the `autocomplete` package.

File: lib/autocomplete-manager.coffee [hunk 17]
```diff
@@ -272,18 +186,166 @@ class AutocompleteManager
...
+  # Public: Finds and returns the content before the current cursor position
+  #
+  # selection - The {Selection} for the current cursor position
+  #
+  # Returns {String} with the prefix of the {Selection}
+  prefixOfSelection: (selection) ->
+    selectionRange = selection.getBufferRange()
+    lineRange = [[selectionRange.start.row, 0], [selectionRange.end.row, @editor.lineTextForBufferRow(selectionRange.end.row).length]]
+    prefix = ''
+    wordRegex = /\b\w*[a-zA-Z_-]+\w*\b/g
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: We should really make this select the prefix by the innermost scope, that way we utilize the language syntax parsing to hint at what is really part of what we are replacing. Might need to make this configurable also so that languages that have bad syntax detection don't break.

Not needed for this round, but we should think about it.

File: lib/autocomplete-manager.coffee (hunk 14 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: I'm not aware of an empty string ever being a valid suggestion...

File: lib/autocomplete-manager.coffee [hunk 18]
```diff
@@ -272,18 +180,166 @@ class AutocompleteManager
...
+        prefixOffset = selectionRange.start.column - range.start.column
+        prefix = match[0][0...prefixOffset] if range.start.isLessThan(selectionRange.start)
+
+    return prefix
+
+  # Private: Checks whether the current file is blacklisted.
+  #
+  # Returns {Boolean} that defines whether the current file is blacklisted
+  currentFileBlacklisted: ->
+    blacklist = (atom.config.get('autocomplete-plus.fileBlacklist') or '')
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: You should be able to use a config schema to type this key as an array, avoiding this string manipulation.

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: I think we do need it for this round. There are some really weird bugs (reported in issues against the current version) related to prefix selection. I have been meaning to write a few tests in this PR to address them.

File: lib/autocomplete-manager.coffee [hunk 19]
```diff
@@ -272,18 +180,166 @@ class AutocompleteManager
...
+    @delayTimeout = setTimeout(@runAutocompletion, delay)
+
+  # Private: Gets called when the cursor has moved. Cancels the autocompletion if
+  # the text has not been changed.
+  #
+  # data - An {Object} containing information on why the cursor has been moved
+  cursorMoved: (data) =>
+    @hideSuggestionList() unless data.textChanged
+
+  editorHasFocus: =>
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: It's hard to imagine the command getting executed if the editor didn't have focus, but perhaps there's a case I'm not considering.

File: lib/autocomplete-manager.coffee [hunk 20]
```diff
@@ -272,18 +180,166 @@ class AutocompleteManager
...
+  bufferChanged: (e) =>
+    return if @suggestionList.compositionInProgress
+    return unless @editorHasFocus()
+    if atom.config.get('autocomplete-plus.enableAutoActivation') and (e.newText.trim().length is 1 or e.oldText.trim().length is 1)
+      @contentsModified()
+    else
+      @hideSuggestionList()
+
+  #  |||              |||
+  #  vvv PROVIDER API vvv
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Appreciate this comment :wink:

File: lib/autocomplete-manager.coffee (hunk 3 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: Could we perhaps just add a 'defaultProviders' registration point, and then register @fuzzyProvider as a default?

File: lib/autocomplete-manager.coffee [hunk 21]
```diff
@@ -272,18 +180,166 @@ class AutocompleteManager
...
+    return @unregisterProviderForGrammars(provider, [grammar])
+
+  unregisterProvider: (provider) =>
+    return unless provider?
+    return @unregisterProviderForScopes(provider, _.keys(@scopes))
+    @subscriptions.remove(provider) if provider.dispose?
+
+  provideApi: =>
+    atom.services.provide 'autocomplete.provider-api', "1.0.0", { @registerProviderForEditor, @unregisterProviderForEditor, @unregisterProvider, Provider, Suggestion }
+    atom.services.provide 'autocomplete.provider-api', '2.0.0', { @registerProviderForGrammars, @registerProviderForScopes, @unregisterProviderForGrammars, @unregisterProviderForScopes, @unregisterProvider }
```
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: We favor exposing disposables returned from the registration methods as the only way to dispose of things, rather than exposing "unregister" methods. Any reason why that couldn't work in this case?

File: spec/provider-spec.coffee [hunk 22]
```diff
@@ -0,0 +1,283 @@
...
+            editor.moveToBeginningOfLine()
+            editor.insertText('f')
+            advanceClock(completionDelay)
+
+            suggestionListView = atom.views.getView(autocompleteManager.suggestionList)
+            atom.commands.dispatch(suggestionListView, 'autocomplete-plus:confirm')
+
+            expect(testProvider.confirm).toHaveBeenCalled()
+
+    describe "Provider API v1.0.0", ->
```
Comment (nathansobo) [inline spec/provider-spec.coffee]: Is there already a 1.0 API in the wild?

File: lib/provider.coffee [hunk 23]
```diff
@@ -22,13 +18,18 @@ class Provider
...
+    @buildSuggestions.apply(this, arguments)
+
   # Public: Gets called when the document has been changed. Returns an array with
   # suggestions. If `exclusive` is set to true and this method returns suggestions,
   # the suggestions will be the only ones that are displayed.
   #
   # Returns An {Array} of suggestions.
   buildSuggestions: ->
-    throw new Error "Subclass must implement a buildWordList(prefix) method"
+    throw new Error 'Subclass must implement a buildWordList(prefix) method'
```
Comment (nathansobo) [inline lib/provider.coffee]: Should this exception say `buildSuggestions`? Also, should this method take a hash containing the prefix, the scope, the cursor position, etc?

File: lib/autocomplete-manager.coffee (hunk 21 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: The only reason this might be difficult is if we had a provider that wanted to be able to provide configuration for what scopes or grammars to which it is applied.  However, in that case it could just be disposed and reregistered when the configuration changes.

File: lib/suggestion-list.coffee [hunk 24]
```diff
@@ -0,0 +1,112 @@
...
+    keys['enter'] = 'autocomplete-plus:confirm' if completionKey.indexOf('enter') > -1
+
+    if @items?.length > 1 and navigationKey == 'up,down'
+      keys['up'] =  'autocomplete-plus:select-previous'
+      keys['down'] = 'autocomplete-plus:select-next'
+    else
+      keys['ctrl-n'] = 'autocomplete-plus:select-next'
+      keys['ctrl-p'] = 'autocomplete-plus:select-previous'
+
+    @keymaps = atom.keymaps.add(
```
Comment (nathansobo) [inline lib/suggestion-list.coffee]: Seems weird to build the keymap programmatically. Why not just use a CSON file on disk for the package? Perhaps our primitive UI for editing keymaps forces you to go through the config API for the confirm key, requiring this approach. But it's unfortunate.

File: lib/autocomplete-manager.coffee [hunk 25]
```diff
@@ -272,18 +186,166 @@ class AutocompleteManager
...
+  # |||              |||
 
   # Public: Clean up, stop listening to events
   dispose: ->
-    @compositeDisposable.dispose()
-    @emitter.emit 'did-dispose'
-
-  onDidDispose: (cb) ->
-    @emitter.on 'did-dispose', cb
+    @editorSubscription?.dispose()
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: should just add this to the primary subscriptions

File: lib/autocomplete-manager.coffee [hunk 26]
```diff
@@ -272,18 +186,166 @@ class AutocompleteManager
...
+    @editorSubscription = null
+    @bufferSavedSubscription?.dispose()
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: when we switch to using a composite subscription for the editor subscriptions, we could just add that to the primary `@subscriptions` so we can go back to disposing just `@subscriptions` here.

**Comment by nathansobo** [comment]
Not sure how broadly I should comment on various things since this mainly deals with using services. I'll start there.

I'm wondering if the consumer-provider relationship should be inverted. So you provide your provider as a service to the autocomplete package, targeting a specific version. Then the autocomplete will consume services that people provide for various versions. Also, I think providers should be based on scope *selectors*. Scope descriptors and scope selectors are different sides of the same coin, but they shouldn't be confused. Selectors are designed for matching.

 So adding a provider would look like this:

```coffee
atom.services.provide "autocomplete.provider", "2.0.0",
  scopeSelector: ".source.ruby .method",
  provide: ({prefix, scope, bufferPosition}) -> # ...
```

Some other thoughts:

* Should we pass an object to the provider containing relevant information? This allows us to expand what we provide over time.
* Do we force subclassing `Provider` for new providers? If so, I don't think we should. The interface should be as simple as possible because subclassing Coffee from other JS languages is a pain.
* Should we make a synchronous `provideSync` method and an async `provide` method? Haven't fully thought through the implications of blending these together, but it does seem like building suggestions might need to support an async API. Of course if things take too long it will be a bad user experience.

File: lib/suggestion-list.coffee [hunk 27]
```diff
@@ -0,0 +1,112 @@
...
+
+  show: (editor) =>
+    return if @active
+    return unless editor?
+    @destroyOverlay()
+
+    marker = editor.getLastCursor()?.getMarker()
+    return unless marker?
+    @overlayDecoration = editor.decorateMarker(marker, { type: 'overlay', item: this })
+    @addKeyboardInteraction()
```
Comment (nathansobo) [inline lib/suggestion-list.coffee]: Even if you do keep the construction of key bindings programmatic, it seems really weird to add and remove the bindings every time you show and hide the overlay.

File: lib/autocomplete-manager.coffee [hunk 28]
```diff
@@ -272,18 +186,166 @@ class AutocompleteManager
...
+  # the text has not been changed.
+  #
+  # data - An {Object} containing information on why the cursor has been moved
+  cursorMoved: (data) =>
+    @hideSuggestionList() unless data.textChanged
+
+  editorHasFocus: =>
+    return false unless @editorView?
+    editorView = @editorView
+    editorView = editorView[0] if editorView.jquery
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: we can probably take this line out now

File: lib/suggestion-list.coffee [hunk 29]
```diff
@@ -0,0 +1,112 @@
...
+    @emitter.on('did-cancel', fn)
+
+  show: (editor) =>
+    return if @active
+    return unless editor?
+    @destroyOverlay()
+
+    marker = editor.getLastCursor()?.getMarker()
+    return unless marker?
+    @overlayDecoration = editor.decorateMarker(marker, { type: 'overlay', item: this })
```
Comment (nathansobo) [inline lib/suggestion-list.coffee]: Minor code style issue: In new code, we typically don't put spaces inside the `{}` characters. The rationale is that you never see this with `[]` characters and its a similar situation.

**Comment by nathansobo** [comment]
I should add that I'm really glad to see you using new APIs such as overlay views. We're interested in your feedback on the experience of using them.

File: lib/autocomplete-manager.coffee (hunk 19 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: The primary use of this is that when we are autocompleting focus is not actually on the editor, but on the hidden input inside the autocomplete.  

The hidden input is a piece of magic that @joefitzgerald and I can't seem to entirely explain how it works.  Some insight there would be nice if you happen to be able to explain how it works.

File: lib/autocomplete-manager.coffee (hunk 9 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: I'd lobby for it just to help keep this file from being so enormous.

File: lib/autocomplete-manager.coffee (hunk 19 above)
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: The hidden input has to be there to handle all types of text input correctly, since everything on screen in the editor is just rendered there with custom code. With the move toward the shadow DOM, the `atom-text-editor` element should finally now expose itself to the outside world as being focused, even when the focus is actually on the hidden input beneath the shadow boundary. That said, I still don't fully understand when this would be false in a typical scenario. Don't you hide the autocomplete when the editor loses focus? But it's not a huge deal.

File: lib/autocomplete-manager.coffee [hunk 30]
```diff
@@ -272,18 +186,166 @@ class AutocompleteManager
...
+    grammars = _.filter(grammars, (grammar) -> grammar?.scopeName?)
+    scopes = _.pluck(grammars, 'scopeName')
+    return @registerProviderForScopes(provider, scopes)
+
+  registerProviderForScopes: (provider, scopes) =>
+    return unless provider?
+    return unless scopes? and _.size(scopes) > 0
+    for scope in scopes
+      existing = _.findWhere(_.keys(@scopes), scope)
+      if existing? and @scopes[scope]?
```
Comment (park9140) [inline lib/autocomplete-manager.coffee]: it seems like one of these checks should be unnecessary.

**Comment by park9140** [comment]
@nathansobo, I've been using overlay views here, and in AtomLinter,  I made a few suggestions that might help keep them usable as more libraries utilize them. https://github.com/atom/atom/issues/4401.

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: Like how typing, `$el` when you have `$element` as a suggestion returns `$$element`.  Bugs the crap out of me :)

**Comment by nathansobo** [comment]
@park9140 Lots of good ideas in there. May take a while to have bandwidth to implement them.

File: lib/main.coffee [hunk 31]
```diff
@@ -10,74 +9,63 @@ module.exports =
...
     fileBlacklist:
-      type: "string"
-      default: ".*, *.md"
-      order: 90
+      title: 'File Blacklist'
+      description: 'Suggestions will not be provided for files matching this list.'
+      type: 'string'
+      default: '.*, *.md'
+      order: 6
+    scopeBlacklist:
```
Comment (park9140) [inline lib/main.coffee]: we should really provide a way to blacklist scopes on an individual provider basis...  There are probably alot of cases where you wouldn't want your provider to even bother firing, such as when you are in a particular grammar, but are in a comment section.

File: lib/suggestion-list-element.coffee [hunk 32]
```diff
@@ -147,11 +145,8 @@ class SelectListElement extends HTMLElement
...
 
-  unmountComponent: ->
-    @dispose()
-
   dispose: ->
     @subscriptions.dispose()
     @parentNode?.removeChild(this)
 
-module.exports = SelectListElement = document.registerElement('autocomplete-suggestion-list', prototype: SelectListElement.prototype)
+module.exports = SuggestionListElement = document.registerElement('autocomplete-suggestion-list', prototype: SuggestionListElement.prototype)
```
Comment (park9140) [inline lib/suggestion-list-element.coffee]: Good rename :)

**Comment by park9140** [comment]
@nathansobo, if you don't get to it first I'll probably throw down a pull request for it, assuming I can make some headway on the rest of my list of things to do.

File: spec/provider-spec.coffee (hunk 22 above)
Comment (joefitzgerald) [inline spec/provider-spec.coffee]: The existing provider API is in main.coffee, and 1.0.0 of the API is designed to match that. It will be deprecated completely, eventually, but this allows people to hop onto service-hub based registration without making drastic changes to their Provider in the short term.

File: lib/main.coffee (hunk 31 above)
Comment (joefitzgerald) [inline lib/main.coffee]: I think that just means we need to support blacklisting of the nested scope. I.e. 'source.js comment` (not an actual scope, just pseudocode) could be used to restrict to the combination of the two scopes.

File: lib/suggestion-list.coffee (hunk 29 above)
Comment (joefitzgerald) [inline lib/suggestion-list.coffee]: :+1: will fix.

File: lib/autocomplete-manager.coffee (hunk 28 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: :+1:

File: lib/suggestion-list.coffee (hunk 27 above)
Comment (joefitzgerald) [inline lib/suggestion-list.coffee]: It's definitely a bit weird, but it solves a defect where (for a single suggestion, where up/down arrows are really not helpful) a user wants to retain their ability to use the up / down arrows to move the cursor.

**Comment by joefitzgerald** [comment]
> I'm wondering if the consumer-provider relationship should be inverted.

Interesting. I had assumed that it is the package providing who is implicitly responsible for providing the service (and managing the versioning of it). If the direction is inverted, how does autocomplete-plus:

* Rev the API
* Know which services to consume?

> Also, I think providers should be based on scope selectors.

Completely agree. Will update the approach accordingly.

So adding a provider would look like this:

> Should we pass an object to the provider containing relevant information? This allows us to expand what we provide over time.

Yes, this is already happening in an options object passed to the provider - which is new. Open to alternate ways to achieve the same outcome.

> Do we force subclassing Provider for new providers? If so, I don't think we should. The interface should be as simple as possible because subclassing Coffee from other JS languages is a pain.

We are also **anti** subclassing and trying to provide a graceful migration path from v1.0.0 of the API to v2.0.0 (which will be Provider class -less prior to the merge of this PR). I also aim to deprecate `Suggestion` and use anonymous objects instead.

> Should we make a synchronous provideSync method and an async provide method? 

That we're even commenting in this PR is a result of two things:

* We want autocomplete to not suck
* We want to add asynchronous support to the Provider API (I need it for go-plus, many others need it) and then make suggestion display asynchronous also (we'll probably initially ship with something that waits for all promises to resolve, and then figure out how to update the suggestion list as suggestions roll in)

Thanks so much for the thorough review in here - great stuff that I will address shortly.

File: lib/suggestion-list.coffee (hunk 24 above)
Comment (joefitzgerald) [inline lib/suggestion-list.coffee]: This is new, created by @park9140 specifically to address #173. It also allows us to simplify the way end-users achieve what is probably the # 1 issue category in this repo: "how do I change the keybindings". That has dropped off precipitously since this was added. We ended up backing out some changes to ensure we can still support user keymaps.

That said, yes - it would be great to evolve this further!

File: lib/provider.coffee (hunk 23 above)
Comment (joefitzgerald) [inline lib/provider.coffee]: We already pass an options object to this method. This method is legacy and will be deprecated.

File: lib/autocomplete-manager.coffee (hunk 19 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: @nathansobo, is there any way we can implement this in a more explicit manner, I would like to switch the suggestion list over to use shadow DOM, however when I do the suggestion list doesn't bubble typing properly.

File: lib/autocomplete-manager.coffee (hunk 28 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: @joefitzgerald, based on @nathansobo's feedback I looked through the uses of this.  I think the entire function and all usages can just be stripped out now.

**Comment by park9140** [comment]
@joefitzgerald, @nathansobo 

> I'm wondering if the consumer-provider relationship should be inverted.

In dependency injection we commonly register multiple services with the same interface and request all impementors of that interface.  @nathansobo, if I am reading the `service-hub` implementation correctly, we could consume `autocomplete-provider` at a particular semver and then we would generate multiple callbacks for each `autocomplete-provider` that has been registered?  If this is not true could we make it true?

File: lib/autocomplete-manager.coffee (hunk 2 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Removed in 1be99bb634ef6137b2070d849fe9cd4cda222de5.

File: lib/autocomplete-manager.coffee (hunk 3 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: So... by far the most predominant pattern for scope matching will be via the grammar's scope. The thought is that providers would be collected in order from the most specific scope to the least specific scope (if any match at all).

Your suggestion around switching from descriptors to selectors is great and we'll switch. Are there any helper functions that can be used to facilitate matching a scope selector against a list of scope selectors, selecting all that match - in order from most specific match to least specific match?

It seems that config and keymaps both do something very similar, so hoping the answer is yes.

File: lib/autocomplete-manager.coffee (hunk 4 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: I like it. :+1:

File: lib/autocomplete-manager.coffee (hunk 1 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: @park9140 I stubbed this out in 77baf6f447ceea085625b35f84682804e05b1180, feel free to implement the method(s).

**Comment by nathansobo** [comment]
@joefitzgerald 

> If the direction is inverted, how does autocomplete-plus:
> * Rev the API

It should be possible to consume providers targeting multiple given interfaces. So autocomplete would consume all providers providing `1.0.0`, `1.1.0`, etc. It might have multiple consumers to shim back to the other interface.

> * Know which services to consume?

It would only consume `autocomplete-plus.provider` services matching known versions.

> if I am reading the service-hub implementation correctly, we could consume autocomplete-provider at a particular semver and then we would generate multiple callbacks for each autocomplete-provider that has been registered?

Yeah, that was the idea. Your callback gets fired with any provided services matching your name and semver range. It's many-to-many.

File: lib/autocomplete-manager.coffee (hunk 4 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Addressed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

**Comment by nathansobo** [comment]
I should add that it's definitely subjective whether packages implementing providers should call `provide` on the service hub. But it does seem like a pretty natural fit. Even the vocabulary matches up.

File: lib/autocomplete-manager.coffee (hunk 28 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Removed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

File: lib/autocomplete-manager.coffee (hunk 15 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: We should verify if this is still necessary, I think it was something to ensure that all the cursors get updated after using autocomplete to modify a set of cursors.

File: lib/autocomplete-manager.coffee (hunk 5 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Implemented in d292524a5617aae2629a8325a2527119fb6ce624.

File: lib/autocomplete-manager.coffee (hunk 6 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

File: lib/autocomplete-manager.coffee (hunk 9 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Okie dokie. Extracting.

File: lib/autocomplete-manager.coffee (hunk 10 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in d292524a5617aae2629a8325a2527119fb6ce624.

File: lib/autocomplete-manager.coffee (hunk 16 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in d292524a5617aae2629a8325a2527119fb6ce624.

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Do you have something reproducible?

File: lib/autocomplete-manager.coffee (hunk 19 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: This was removed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

File: lib/autocomplete-manager.coffee (hunk 25 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

File: lib/autocomplete-manager.coffee (hunk 26 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Fixed in fb0c8c36984b90e10c40760c01e4aae30d422b18.

File: lib/autocomplete-manager.coffee (hunk 30 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: existing? implies the key exists. @scopes[scope]? implies the value is defined. It's possible - although highly unlikely - it's undefined.

This will likely change when we switch to selectors instead of descriptors.

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: Right now the only time I see this is in `atom-typescript-tools` since the typescript autocomplete providers provides the completions with the `$` in them.

**Comment by joefitzgerald** [comment]
@nathansobo Many providers will want to provide for many scopes. Would you see it as idiomatic to provide for each specific scope, or would it be better for us to accept an array of selectors?

```
atom.services.provide "autocomplete.provider", "2.0.0",
  scopeSelector: ".source.ruby .method",
  provide: ({prefix, scope, bufferPosition}) -> # ...
```

There's also the case of a provider which should be run always (e.g. `autocomplete-snippets`).

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: It certainly feels like we should find some way to leverage the grammars to do the heavy lifting to determine prefix by default. The current method is clunky and causing too many bugs.

File: lib/autocomplete-manager.coffee (hunk 15 above)
Comment (joefitzgerald) [inline lib/autocomplete-manager.coffee]: Here's where it came from. Wonder if that suffix is relevant to our issues...

https://github.com/atom/autocomplete/blob/aa449af36b8c2fa2e0ca07883e793e891ad07d2b/lib/autocomplete-view.coffee#L82-L84

**Comment by park9140** [comment]
@nathansobo, I really like this switch to having the api providers calling service hub.  It clears up my previous concerns about providers needing to all implement disposability since it seems more natural for a provided service to implement `onDispose()`

@joefitzgerald 
> Many providers will want to provide for many scopes. Would you see it as idiomatic to provide for each specific scope, or would it be better for us to accept an array of selectors?

It seems to me that we may want to think of the service registration as just that.  The `providers`, all provide an instance of the same completion interface,  so the service everything could be providing is, `auto-complete.completions`.  

We should really think about making the interface provide the category of completions, so that we can make a configuration that sorts by category.  If we had this and defaulted, `fuzzyprovider` to something like `fallback` and default the configuration so that `fallback` category is always last, we could allow other providers to provide similar functionality and not write extra code for the fuzzy provider.

**Comment by nathansobo** [comment]
@joefitzgerald  Selector strings can also have `,` in them to target multiples, so it seems like that could be used rather than an array of multiple strings. This would still force you to call `provide` once for each scope selector you wanted to match against. An alternative would be to call `provide` with an object mapping scope selectors to provider functions, but there's less room to give providers other methods in the future.

**Comment by joefitzgerald** [comment]
@park9140 >> https://gitter.im/atom-community/autocomplete-plus 

As an aside, `FuzzyProvider` = pile of :hankey:. I only keep it around until we have a chance to spur a provider writing contest (perhaps with the assistance of the Github team), after which time I believe it's an anti-pattern to have a fallback.

Said another way: autocomplete-plus should provide suggestions if it has good suggestions that are contextually informed. If it cannot, it should not provide suggestions at all.

**Comment by nathansobo** [comment]
Do you already have a 1.0 interface via the service hub? If not, might I suggest using `0.x` versions while this API is in flux?

**Comment by joefitzgerald** [comment]
> Do you already have a 1.0 interface via the service hub? If not, might I suggest using 0.x versions while this API is in flux?

This won't be merged until the API is cemented. But no, there is no existing 1.0 interface via service-hub. We could modify the version for the existing API to 0.1.0, and make the new API 0.2.0.

**Comment by nathansobo** [comment]
> Said another way: autocomplete-plus should provide suggestions if it has good suggestions that are contextually informed. If it cannot, it should not provide suggestions at all.

I've always been a huge fan of "matching word from an open buffer". It's not intelligent, but it can often be pretty productive. I often prefer it to "smarter" completion because its behavior is so regular. One huge improvement in my mind would be to sort the matching words by proximity to the current location since locality is usually a good predictor of appropriateness.

> We could modify the version for the existing API to 0.1.0, and make the new API 0.2.0.

Does it even make sense to provide the existing API via the service hub? Why not expose the new API from day 1 and just keep the existing API on the main module as it currently is?

File: lib/autocomplete-manager.coffee (hunk 17 above)
Comment (park9140) [inline lib/autocomplete-manager.coffee]: Yeah.

File: lib/autocomplete-manager.coffee (hunk 15 above)
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: Yeah in that case it makes more sense because the column is actually modified. In this case it's the exact same values so it seems like a no-op.

**Comment by joefitzgerald** [comment]
> Does it even make sense to provide the existing API via the service hub? Why not expose the new API from day 1 and just keep the existing API on the main module as it currently is?

@nathansobo The only reason would so we can deprecate and remove the mainModule API very quickly. But I'm not tied to providing it that way. What I do know is that the last time we made a breaking change, it caused a bunch of issues, and this might be a halfway house that allows us to guide people through the change a little more smoothly.

Reality is we may just make PRs against the most used providers and call it a day.

**Comment by joefitzgerald** [comment]
@nathansobo is there a selector for all scopes?

File: lib/autocomplete-manager.coffee (hunk 3 above)
Comment (nathansobo) [inline lib/autocomplete-manager.coffee]: You might try using the [`scoped-property-store`](https://github.com/atom/scoped-property-store] library which config uses for scoped config values. You wouldn't need to use the key-path features but the scope matching ones would serve the use-case well. We recently added a [`getAll`](https://github.com/atom/scoped-property-store/blob/master/src/scoped-property-store.coffee#L78) method that can return all values for a given scope ordered by specificity.

**Comment by nathansobo** [comment]
> The only reason would so we can deprecate and remove the mainModule API very quickly.

My instinct is to deprecate the main module API and leave it in place for a while since it's doing no harm. You can use `grim` to actually warn its users. Then you can focus on exposing a newer, better API via the service hub moving forward. If you want to maintain the old API forever via the service-hub then I guess it makes sense to provide it, but it might be nice to cut to the new one so long as people are making changes.

> is there a selector for all scopes?

`*` should match anything, if I understand your question correctly.

**Comment by nathansobo** [comment]
Depending on the API, you could default to `*` if they don't provide a selector. Obviously if you use the route of using selectors as keys in an object you couldn't default it and people would have to use `*` explicitly.

**Comment by joefitzgerald** [comment]
@nathansobo Would you mind joining us in https://gitter.im/atom-community/autocomplete-plus? We want to discuss dispose semantics in the inverted model you described.

**Comment by joefitzgerald** [comment]
@nathansobo This is ready to :ship:. Would appreciate your review of the code as it currently stands. This includes use of scoped-property-store for storage of provider registrations and the global / provider blacklists. We have also inverted the service-hub directionality, `autocomplete+` is now the `consumer` of providers.
